improve(relayer): Drop slow fill request queries
across-protocol/relayer-v2 pull request #1340
Opened 2024-03-21 22:12 UTC by pxrl

By retaining the deposit FillStatus on the destination chain it's possible to skip scraping for RequestedV3SpeedUp events. This reduces the RPC load during SpokePoolClient update.

2024-03-21 22:13 UTC, pxrl commented on src/relayer/Relayer.ts
> +    if (slowDepositors?.includes(depositor) && fillStatus === FillStatus.Unfilled) {
Opinionated driveby change: If the operator has configured `SLOW_DEPOSITORS`, then don't require `SEND_SLOW_RELAYS` to be enabled.

2024-03-21 22:13 UTC, pxrl commented on src/relayer/Relayer.ts
> -      if (sendSlowRelays) {
Opinionated driveby change: If the operator has configured SLOW_DEPOSITORS, then don't require SEND_SLOW_RELAYS to be enabled.

2024-03-21 22:14 UTC, nicholaspai approved these changes
This also seems good

2024-03-21 22:14 UTC, nicholaspai commented on src/relayer/Relayer.ts
> -      if (sendSlowRelays) {
why not? not sure I agree

2024-03-21 22:33 UTC, james-a-morris reviewed
Although I agree that a slow depositor should trigger a slow relay every time, I'm not sure we want to remove the configuration to be able to disable slow relays from a given relayer.

2024-03-21 22:44 UTC, pxrl commented
> Although I agree that a slow depositor should trigger a slow relay every time, I'm not sure we want to remove the configuration to be able to disable slow relays from a given relayer.

Agree - that's not changed here and it remains as-is :+1: Slow relays is still 100% opt-in.

2024-03-21 23:13 UTC, pxrl commented on src/relayer/Relayer.ts
> -      if (sendSlowRelays) {
The current configuration gives no way to opt-in to slow fill specific addresses and to ignore all others. Meanwhile, if the operator has explicitly defined an array of addresses to fill with slow relays, I see that as an implicit opt-in to slow relays for those addresses, and it shouldn't be required to separately enable slow fills for all other addresses.

This doesn't mean that the relayer would make slow fills for all other deposits - only for addresses identified in `slowDepositors`. The existing `sendSlowRelays` conditional still applies to everything else.

2024-03-22 00:46 UTC, nicholaspai reviewed
I think this will also cause bundle refund construction problematic since we need slow fill requests to compute bundle data correctly

2024-03-22 00:47 UTC, nicholaspai requested changes
do not merge yet until bundle data can be fetched without using SlowFillRequest events

2024-03-22 09:57 UTC, pxrl commented
> I think this will also cause bundle refund construction problematic since we need slow fill requests to compute bundle data correctly

That's important for the proposer/disputer, but is relevant for the relayer? This PR only affects the relayer's SpokePoolClient update, and deposit update requests don't affect relayer repayments so I can't see any obvious problem with ignoring them.

2024-04-05 15:34 UTC, nicholaspai approved these changes
I think we can revisit this now that we load most bundle data from arweave. I also think this probably wasn't an issue affecting bundle refund computation

2024-04-05 21:38 UTC, pxrl commented
> I think we can revisit this now that we load most bundle data from arweave. I also think this probably wasn't an issue affecting bundle refund computation

Yeah - I also wasn't able to reason my way to any problem with dropping these events. I'll merge this on Monday :+1:

2024-04-09 07:49 UTC, merged