feat(finalizer): Add support for lookback in seconds (instead of blocks)
across-protocol/relayer-v2 pull request #378
Opened 2022-11-30 17:46 UTC by kevinuma

Context:
Currently the finalizer sets the lookback for fetching transfer/finalization events using number of blocks. However, as the block production rate varies, the finalizer can sometimes fall short (lookback is not enough to cover all deposits). It's also easier for operators to set the config if it's duration instead of number of blocks.

2022-11-30 17:48 UTC, kevinuma commented on src/finalizer/index.ts
> +  if (config.maxFinalizerLookbackSecs > 0) {
I'm using this as a feature flag so we can enable/disable this new timestamp-based lookup easily

2022-12-02 00:09 UTC, mrice32 approved these changes
Looks great! Only minor nits.

2022-12-02 00:09 UTC, mrice32 commented on src/common/ClientHelper.ts
> +  for (const strChainId of Object.keys(lookbackSecs)) {
nit: prefer .map() when you're just trying to return an array of the same length as the thing you're looping over.

nit: prefer Object.entries() when using both the key and value, since it returns a list of pairs of keys and values.

2022-12-02 00:09 UTC, mrice32 commented on src/common/ClientHelper.ts
> +  }
nit: prefer Object.fromEntries when creating an object from an array where each element corresponds to one key/value pair.

2022-12-11 15:44 UTC, nicholaspai commented on src/common/ClientHelper.ts
> +  lookbackSecs: { [chainId: number]: number } = {}
This is a good point I think we want the same lookback for all chains actually, that's the main benefit of this PR: condense a dictionary of lookback blocks into a single lookback time

2022-12-12 13:50 UTC, pxrl commented on src/common/Constants.ts
>  };
I see - will be removed later.

2022-12-16 19:01 UTC, nicholaspai requested changes
requesting changes to matt's review

2022-12-21 23:34 UTC, closed without merging

2022-12-21 23:34 UTC, nicholaspai commented
Replacing with #395