chore(config): Prevent non-zero POLLING_DELAY
across-protocol/relayer-v2 pull request #438
Opened 2023-01-26 09:24 UTC by pxrl

This is an administrative change to temporarily prevent operators from running in
looping mode. The justification for this is that we currently do not apply the same
QA to non-zero polling delay (looping mode) as we do to serverless mode.

Looping mode is useful for third-party operators and the intention is ultimately to
support it.

2023-01-26 11:58 UTC, nicholaspai commented on src/common/Config.ts
> +    this.pollingDelay = Number(POLLING_DELAY ?? 0);
`pollingDelay` is used in many other files in this repo can you do a search and remove those instances/branches?

2023-01-26 11:59 UTC, nicholaspai requested changes
https://github.com/across-protocol/relayer-v2/pull/438/files#r1087757261

2023-01-26 14:36 UTC, pxrl commented on src/common/Config.ts
> +    this.pollingDelay = Number(POLLING_DELAY ?? 0);
I found 19 instances of "polligDelay" in the code, but this is the only place where it's set, so all of the existing code should continue to run OK as it does in the prod environment.

Note I'm assuming that we only want to disable this functionality until we determine how to properly test and support a non-zero POLLING_DELAY. If we don't want to support it at all then it would definitely make sense to remove it.

In general I'd like to see it retained as a future possibility, because there are a few overheads during startup for the bot. Some of these overheads should become smaller as we get caching of getLogs requests in redis. wdyt?

2023-01-26 20:38 UTC, pxrl commented on test/Monitor.ts
> +      POLLING_DELAY: "60",
I consider this specific change to be a bodge, since the test fails without it. Per current implementation the Monitor test seems to only work with a non-zero polling delay. This one needs a bit more investigation.

2023-02-01 15:21 UTC, nicholaspai commented on src/common/Config.ts
> +    this.pollingDelay = Number(POLLING_DELAY ?? 0);
Hm ok I see so this PR amounts to defaulting to 0 instead of "preventing" non zero

2023-02-01 15:22 UTC, nicholaspai commented on test/Monitor.ts
> +      POLLING_DELAY: "60",
This is definitely a bodge/hack. I'd feel more comfortable if we knew why this test only works with polling delay = 60, and fixed it so that it works with 0. This is because we run monitor with polling delay = 0 in prod so the test would be closer to prod

2023-02-01 16:18 UTC, pxrl commented on src/common/Config.ts
> +    this.pollingDelay = Number(POLLING_DELAY ?? 0);
It does two things:
 - If POLLING_DELAY is not env-specified, change the default from 60 to 0.
 - If POLLING_DELAY is env-specified and is NOT 0, assert to prevent further execution.

2023-03-01 08:13 UTC, closed without merging