feat: add tsconfig strict and modify eslint
across-protocol/relayer-v2 pull request #552
Opened 2023-04-03 17:54 UTC by james-a-morris

This PR performs various refactors across the relayer to improve developer experience and reduce errors from common linting patterns.

2023-04-03 18:29 UTC, pxrl commented on src/utils/ContractUtils.ts
> +  return fragment.inputs.find((input: { name: string }) => input.name === paramName) || "";
Curious on this one - I presume fragment can theoretically be undefined, so it's interesting that we don't get a warning when unconditionally dereferencing it on line 32.

nb. I don't think this is too important, since this is likely something that will always fail or never fail, and it obviously works OK now.

2023-04-03 18:34 UTC, james-a-morris commented on src/utils/ContractUtils.ts
> +  return fragment.inputs.find((input: { name: string }) => input.name === paramName) || "";
I left the `strictNullChecks: false` parameter to prevent a significant overhaul of logic. As a result, the `undefined` values are not considered warnings.

2023-04-03 18:38 UTC, pxrl commented on tasks/integration-tests.ts
> +    transports: transports,
```suggestion
    transports,
```

2023-04-03 18:39 UTC, pxrl approved these changes
LGTM - lots of changes, but it gives some comfort knowing that we've been through them once before. I did spot a few minor points, but no showstoppers.

2023-04-03 19:01 UTC, james-a-morris commented on src/utils/TransactionUtils.ts
> +  | {
No worries! This is a way to put the union types on a separate line: https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#discriminating-unions

2023-04-03 20:20 UTC, mrice32 reviewed
Just one comment on the tsconfig!

2023-04-03 20:20 UTC, mrice32 commented on tsconfig.json
> +  "strict": true,
Does this work?

I think this option goes inside compilerOptions, no? Not sure what it does outside. Does it still compile if you move it into compilerOptions?

See https://github.com/tsconfig/bases/blob/7db25a41bc5a9c0f66d91f6f3aa28438afcb2f18/bases/node18.json#L10 as an example.

2023-04-04 23:10 UTC, pxrl commented on tsconfig.json
> +  "strict": true,
I tried migrating it into compilerOptions but I get 246 errors trying to build. Placing it inside compilerOptions also seems to be correct [per the docs](https://www.typescriptlang.org/tsconfig#compilerOptions).

2023-04-04 23:23 UTC, pxrl commented on src/clients/SpokePoolClient.ts
> +
```suggestion
```

2023-04-04 23:44 UTC, pxrl requested changes
Given the number of things that break when strict: true is migrated into the compilerOptions section, maybe we should just remove strict: true for now in order to get this in as-is and then incrementally tackle the remaining issues. I think it's an acceptable approach, because this PR _does_ implement a lot of good changes. Alternatively, it seems like this PR will need to remain open for a longer period, and we'll risk hitting more merge conflicts.

2023-04-05 14:19 UTC, james-a-morris commented
> Given the number of things that break when strict: true is migrated into the compilerOptions section, maybe we should just remove strict: true for now in order to get this in as-is and then incrementally tackle the remaining issues. I think it's an acceptable approach, because this PR _does_ implement a lot of good changes. Alternatively, it seems like this PR will need to remain open for a longer period, and we'll risk hitting more merge conflicts.

This is a fair point! I have a PR open to enable 5 of the 7 strict parameters https://github.com/across-protocol/relayer-v2/pull/559

2023-04-05 14:19 UTC, james-a-morris commented on tsconfig.json
> +  "strict": true,
I have this resolved in this PR: https://github.com/across-protocol/relayer-v2/pull/559

2023-04-05 20:38 UTC, pxrl approved these changes
LGTM!

2023-04-05 20:39 UTC, pxrl commented on tsconfig.json
> +  "strict": true,
```suggestion
```

Can maybe leave this one out, given that it doesn't do what we thought, and this is being merged into master.

2023-04-05 21:08 UTC, james-a-morris commented on tsconfig.json
> +  "strict": true,
Fair - there is an open PR which removes this and it's planned to be merged into this branch prior to this branch's merge into master.

2023-04-05 21:41 UTC, pxrl commented on tsconfig.json
> +  "strict": true,
Ah nice - perfect.

2023-04-06 04:07 UTC, mrice32 reviewed
Looks awesome! Only minor nits and questions! Big step in improving the state of the codebase!

2023-04-06 04:07 UTC, mrice32 commented on src/clients/BundleDataClient.ts
> +    const allRelayerRefunds: { repaymentChain: string; repaymentToken: string }[] = [];
These sorts of changes are great! Going to make the codebase much safer. +1

nit: why use string for chainId?

2023-04-06 04:07 UTC, mrice32 commented on src/utils/ContractUtils.ts
> +  const artifact = typechain[`${[contractName]}__factory`];
❤️

2023-04-06 04:07 UTC, mrice32 commented on tasks/integration-tests.ts
> +  }
+1 way more clear

2023-04-06 13:33 UTC, james-a-morris commented on scripts/unwrapWeth.ts
> +  const token = WETH_ADDRESSES[Number(args.chainId) as keyof typeof WETH_ADDRESSES];
Resolved https://github.com/across-protocol/relayer-v2/pull/565

2023-04-06 14:02 UTC, james-a-morris commented on src/clients/BundleDataClient.ts
> +    const allRelayerRefunds: { repaymentChain: string; repaymentToken: string }[] = [];
Fair point! Resolved in a companion PR (that will be merged in here): https://github.com/across-protocol/relayer-v2/pull/566/commits/c20f84be403fb0f1570b2a861fd2e672a0e17f0c

2023-04-06 14:10 UTC, james-a-morris commented on .eslintrc.js
> +    "no-console": 0,
Fair point - I've reverted the eslint back to the master branch. https://github.com/across-protocol/relayer-v2/pull/566/commits/62f9c2f4e243a965b238e941aab286f7389c0296

2023-04-06 14:10 UTC, james-a-morris commented on .eslintrc.js
> -    "mocha/no-exclusive-tests": "error",
Similar to above: https://github.com/across-protocol/relayer-v2/pull/566/commits/62f9c2f4e243a965b238e941aab286f7389c0296

2023-04-06 14:10 UTC, james-a-morris commented on .eslintrc.js
> -    "@typescript-eslint/no-var-requires": "off",
Similar to above: https://github.com/across-protocol/relayer-v2/pull/566/commits/62f9c2f4e243a965b238e941aab286f7389c0296

2023-04-06 14:10 UTC, james-a-morris commented on scripts/unwrapWeth.ts
> -  number: ["chainId"],
The official TS documents don't specify `number` as a valid option type. Here are the defined types:
```
declare namespace minimist {
    interface Opts {
        /**
         * A string or array of strings argument names to always treat as strings
         */
        string?: string | string[] | undefined;

        /**
         * A boolean, string or array of strings to always treat as booleans. If true will treat
         * all double hyphenated arguments without equals signs as boolean (e.g. affects `--foo`, not `-f` or `--foo=bar`)
         */
        boolean?: boolean | string | string[] | undefined;

        /**
         * An object mapping string names to strings or arrays of string argument names to use as aliases
         */
        alias?: { [key: string]: string | string[] } | undefined;

        /**
         * An object mapping string argument names to default values
         */
        default?: { [key: string]: any } | undefined;

        /**
         * When true, populate argv._ with everything after the first non-option
         */
        stopEarly?: boolean | undefined;

        /**
         * A function which is invoked with a command line parameter not defined in the opts
         * configuration object. If the function returns false, the unknown option is not added to argv
         */
        unknown?: ((arg: string) => boolean) | undefined;

        /**
         * When true, populate argv._ with everything before the -- and argv['--'] with everything after the --.
         * Note that with -- set, parsing for arguments still stops after the `--`.
         */
        '--'?: boolean | undefined;
    }
}
```

2023-04-06 14:59 UTC, mrice32 commented on scripts/unwrapWeth.ts
> -  number: ["chainId"],
Great find! I'm not sure how "number" ever worked!

TLDR: I think making this a string is the right call. +1!

I found this in their docs: https://github.com/minimistjs/minimist/blob/093bc85eb9b2a06f0d7fa3f7f1940cd135495abf/README.md?plain=1#L64.

Basically if the argument isn't labeled a string or bool and it looks like a number, it will treat it as a number. However, I think treating numbers as strings gives us much more type safety since we know it will always come as a string vs being conditional on the input.

2023-04-06 15:00 UTC, mrice32 commented on src/clients/BundleDataClient.ts
> +    const allRelayerRefunds: { repaymentChain: string; repaymentToken: string }[] = [];
Sounds good!

2023-04-06 16:37 UTC, mrice32 approved these changes
LGTM!

2023-04-06 16:37 UTC, mrice32 commented on .eslintrc.js
> +    "no-console": 0,
I think changing this is totally fine!! I was only calling out potential issues that I saw! Not necessary to completely revert IMO. Ultimately up to you, but I do think there is value in simplicity of the config, which seems to be what you're pushing for 👍

2023-04-07 15:22 UTC, merged