chore: bump sdk version
across-protocol/relayer-v2 pull request #852
Opened 2023-08-03 20:31 UTC by james-a-morris

Closes: ACX-1336

2023-08-04 19:21 UTC, nicholaspai commented on src/utils/FillUtils.ts
> +    hubPoolClient.configStoreClient.getEnabledChains()
```suggestion
    hubPoolClient.configStoreClient.getEnabledChains(latestMainnetBlock)
```

2023-08-04 19:22 UTC, nicholaspai commented on test/ConfigStoreClient.ts
> +      const allPossibleChains = [1, 19, 21, 23];
Why do you need to inject this int this test, shouldn't it just read directly from the `configStore`?

2023-08-04 19:29 UTC, nicholaspai commented on test/ConfigStoreClient.ts
> +      configStoreClient.setAvailableChains([]);
This is a weird test to me. It's testing the MockConfigStoreClient, right?  As opposed to the actual ConfigStoreClient we care about?

2023-08-04 22:02 UTC, nicholaspai approved these changes
This LGTM, as discussed offline i think all its missing are some unit tests for the new SDK imported function you added most recently `getChainIdIndicesForBlock`

2023-08-04 22:30 UTC, james-a-morris commented
@nicholaspai this should resolve the outstanding need for the addtl tests. However, I'm waiting on this PR ( https://github.com/across-protocol/sdk-v2/pull/355 ) to get the tests to pass as I've encoded the new protocol contracts as a constant

2023-08-05 03:24 UTC, nicholaspai commented on test/ConfigStoreClient.ts
> +    expect(configStoreClient.getChainIdIndicesForBlock(eventThree.blockNumber)).to.deep.equal([
This is a great set of tests!

2023-08-05 04:35 UTC, nicholaspai requested changes
I'm just realizing this behavior will be overrided unless you remove `chainIdListIndices` from the common/Config.ts file

Additionally, this PR from the SDK needs to be incorporated: https://github.com/across-protocol/sdk-v2/pull/356

2023-08-07 10:25 UTC, pxrl commented on src/common/Config.ts
> -      : Constants.CHAIN_ID_LIST_INDICES;
It'd be nice to retain some way of overriding the chain ID list via the environment. Otherwise it's a bit more difficult to test new chains before they are added to the global config.

2023-08-07 12:13 UTC, pxrl commented on src/common/Config.ts
> +    // Min deposit confirmations seems like the most likely constant to have all possible chain IDs listed.
This is probably OK for now, but as the bots become more dynamic I think we'll ultimately need to split our verification into pre- and post update stages.

2023-08-07 12:18 UTC, pxrl commented on src/finalizer/index.ts
> +            : commonClients.configStoreClient.getChainIdIndicesForBlock()
In general I'm not keen on reading from `process.env` directly in application code, although sometimes it's difficult or impractical to avoid. In this case I think it'd be preferable to allocate this to a new `FinalizerConfig.ts` file, mirroring the approach for the relayer and dataworker.

It is however a bit unrelated to ACX-1336, so we could consider doing it that separately.

2023-08-07 12:20 UTC, pxrl commented on src/monitor/MonitorConfig.ts
> +    const allPossibleChainIds = Object.keys(MIN_DEPOSIT_CONFIRMATIONS).map((chainId) => Number(chainId));
Rather than recreating from MIN_DEPOSIT_CONFIRMATIONS, I think it'd be better to set `this.allPossibleChainIds` in the `CommonConfig` class, and then everyone else can read from it. It doesn't really make sense to me that the monitor should know anything about MDCs.

2023-08-07 12:22 UTC, pxrl commented on src/relayer/RelayerConfig.ts
> +        Object.keys(this.minDepositConfirmations[threshold]).forEach((chainId) => {
Same as previous - I think it's safer and more maintainable to infer and store `allPossibleChainIds` centrally.

2023-08-07 15:52 UTC, james-a-morris commented on test/Dataworker.loadData.ts
> -    );
These two tests can now be removed as the hubpool/config store is essentially required to be updated

2023-08-07 16:38 UTC, james-a-morris commented on test/ConfigStoreClient.ts
> +      JSON.stringify([1, 10, 137, 288, 42161, 100])
My only worry about this is that I wanted to keep things explicit because we introduce erroneous configs in later tests

2023-08-07 16:38 UTC, james-a-morris commented on src/finalizer/index.ts
> +            : commonClients.configStoreClient.getChainIdIndicesForBlock()
@pxrl Should we make this a separate linear issue?

2023-08-07 16:48 UTC, nicholaspai commented on src/monitor/MonitorConfig.ts
> +    const allPossibleChainIds = Object.keys(MIN_DEPOSIT_CONFIRMATIONS).map((chainId) => Number(chainId));
We'll fix this in #ACX1390

2023-08-07 16:48 UTC, nicholaspai commented on src/finalizer/index.ts
> +            : commonClients.configStoreClient.getChainIdIndicesForBlock()
We'll fix this in #ACX1390

2023-08-07 17:44 UTC, james-a-morris commented on test/ConfigStoreClient.ts
> +      JSON.stringify([1, 10, 137, 288, 42161, 100])
Good call - I've modified for better readability

2023-08-07 18:40 UTC, james-a-morris commented on test/UBAClientUtilities.ts
> +      1000
By increasing the random jump vector, we effectively make the chance of block collisions much smaller

2023-08-07 18:40 UTC, james-a-morris commented on test/utils/HubPoolUtils.ts
> +  });
The motivation here is that we can further enforce that any random errors can be accounted for

2023-08-07 18:40 UTC, nicholaspai commented on src/relayer/RelayerConfig.ts
> +        Object.keys(this.minDepositConfirmations[threshold]).forEach((chainId) => {
https://github.com/across-protocol/relayer-v2/pull/858

2023-08-07 18:51 UTC, pxrl commented on test/utils/BlockchainUtils.ts
>      await hre.network.provider.send("evm_mine");
I'm not sure whether these requests are always synchronous - in my experience it's more like sending a request to hre, and have definitely seen that can return without producing a new block. If you want to be sure that the block is actually mined, I'd recommend periodically issuing `evm_mine` requests until the expected block number is actually produced.

FWIW I had to do something similar here: https://github.com/across-protocol/relayer-v2/blob/2727ef9f298abc9515206f22b990b122c4323e8e/test/Relayer.RefundRequests.ts#L54

2023-08-07 19:11 UTC, nicholaspai commented on test/UBAClientUtilities.ts
> +      1000
Can you add this comment above the hardcoded 1000 just so we know what's going on if this breaks in a future test?

2023-08-07 19:11 UTC, nicholaspai approved these changes
Just one comment LGTM

2023-08-07 19:28 UTC, james-a-morris commented on test/UBAClientUtilities.ts
> +      1000
Done:

```
      // We can override the jump block to be 10_000. By increasing the random jump vector, we
      // can minimize the chance of block collisions that would cause this function to
      // nondeterministically fail in the CI. NOTE: a failure as a result of incorrect
      // block ranges isn't necessarily a failure of the test, but of the randomness that
      // is generated in the test environment to simulate the block ranges.
      10_000
```

2023-08-07 19:39 UTC, james-a-morris commented on test/utils/BlockchainUtils.ts
>      await hre.network.provider.send("evm_mine");
Good call - I think is more-or-less just used to set larger numbers than waiting the random 0 to 10 rate

2023-08-07 21:44 UTC, merged